name: Discord Hook

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
        - name: Test Success
          uses: rjstone/discord-webhook-notify@v2.2.1
          with:
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
              severity: info
              details: All tests passed!
        - name: Discord notification
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          uses: Ilshidur/action-discord@0.4.0
          with:
            args: 'The project has been deployed.'